### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by egze** [machinio/cuprite#101]
Please consider adding a changelog. It will be much easier to check what changed during gem updates.

**Comment by route** [comment]
@egze Agreed, will add one. Thanks!

**Comment by route** [comment]
Since now this gem uses https://github.com/route/ferrum this makes things harder to log, but I'll try closer to 1.0

**Comment by zedtux** [comment]
Any news on this one? It's really painful to read the commits history :disappointed:

**Comment by route** [comment]
I added Changelog for Ferrum, not for Cuprite so far. Mostly work is going for Ferrum and Cuprite is only updating deps

**Comment by zedtux** [comment]
Well not really when I look at [the diff between version 0.14.2 and 0.14.3](https://github.com/rubycdp/cuprite/compare/v0.14.2...v0.14.3). Upgrading the version broke some code in my app, and having the `CHANGELOG.md` highlighting the updates would have save some time for me.

That being said, I understand that most of the work is done in ferrum.

**Comment by route** [comment]
@zedtux added ;) https://github.com/rubycdp/cuprite/pull/237
