### ISSUE TITLE
:logger option is dead

### ISSUE THREAD

**Issue by edlebert** [machinio/cuprite#110]
There used to be a way to send console.log to stdout using CUPRITE_DEBUG.  That's now gone, but the README still references "debug output" sent to the ":logger", but I searched the code and the only place "logger" appears is in the README.

Can you clarify in the README the correct way to send console output to STDOUT?

**Comment by edlebert** [comment]
Nevermind, I'm a moron.

**Comment by route** [comment]
Thanks for catching, it’s now FERRUM_DEBUG but  I think we can alias. I’ll fix in the next release

**Comment by edlebert** [comment]
poltergiest sent all console.log statements to STDOUT. Is there something similar for cuprite?

**Comment by route** [comment]
Yes it's the same logger option, if there's logger you should see console output in there. Maybe you just missed it with tons of other lines. Here's implementation and example https://github.com/route/ferrum/search?q=console&unscoped_q=console

**Comment by henrik** [comment]
Regarding those tons of other lines – is there a recommended way to get console.log output without seeing all that debug output? With Poltergeist and Apparition I've used `console.log` to help debug issues, but this is a bit overwhelming.

I realise I could grep the output or build a custom logger that does it – just checking if there's something built in.

**Comment by route** [comment]
I think we can use STDERR for that, but it's not implemented. @henrik could you please open an issue, I'll try to implement it.

**Comment by henrik** [comment]
@route Done: https://github.com/machinio/cuprite/issues/113 Thank you!

My ugly workaround for now is:

```
rspec foo_spec.rb | grep -v "▶" | grep -v "◀" | grep -v "^$"
```
