### ISSUE TITLE
How to `send_keys` to current focused element?

### ISSUE THREAD

**Issue by vizcay** [machinio/cuprite#111]
I'm and testing a complex application where I need to `send_keys` to simulate shortcuts user behaviour.

With `selenium-webdriver` we can do `page.driver.browser.action.send_keys([..]).perform` and it just works. Cuprite has a similar API?

The only thing we were able to do is `page.evaluate_script('document.activeElement').send_keys(keys)` but `evaluate_script` is taking a lot to return (maybe I should open an issue about that also, because is around 0.5~1sec).

**Comment by route** [comment]
It supports Poltergeist style, take a look at specs we have https://github.com/machinio/cuprite/blob/master/spec/integration/driver_spec.rb#L1262

No need to use `evaluate_script`

**Comment by vizcay** [comment]
Hi @route, sorry maybe I wasn't clear enough with the original post but all the specs pointed work by selecting first the event target (input, textarea, etc) and that is precisely whay I'm trying to avoid as is complex and unnecesary in my case.

`page.driver.browser.action.send_keys([..]).perform` just sends the events to the currently focused element.

Let me show you an example where I need this:

<img width="568" alt="input_table" src="https://user-images.githubusercontent.com/4545990/72893111-09f71d80-3cf7-11ea-822e-cca242bdba97.png">

The table inside must be all navegable with keyboard shortcuts, all I care is that when the user presses `["Sales", :return, :return, "1000", :return, :return]` it does the correct thing, by selecting the next input in the table etc.

**Comment by route** [comment]
I believe there's no currently a shortcut for that because it is bound to a node, but the closest would be `page.driver.browser.keyboard.type("Hello")`

**Comment by vizcay** [comment]
👍 Great. Worked as expected:

```
def global_send_keys(keys)
      Array(keys).each do |key|
          page.driver.browser.keyboard.type(key)
      end
end
```

**Comment by route** [comment]
Glad to hear that!
