### ISSUE TITLE
How best to deal with "there are still pending connections"?

### ISSUE THREAD

**Issue by henrik** [machinio/cuprite#112]
Hi,

Moving some tests over from PhantomJS/Poltergeist and seeing errors like:

     Ferrum::StatusError:
       Request to http://127.0.0.1:43540/foos/1?login_url=http%3A%2F%2Fexample.com%2Flog_in&signup_url=http%3A%2F%2Fexample.com%2Fsign_up reached server, but there are still pending connections: http://127.0.0.1:43540/assets/opensans/opensans-semibold-webfont.ttf, http://lorempixel.com/160/100/cats/6, http://127.0.0.1:43540/message-bus/223b1301317e442687eafc4e32771b39/poll?dlp=t

So a web font loaded from the local server, an image loaded from a remote server, and a MessageBus request to the local server.

We tried increasing `timeout` to 10 seconds, but still get a lot of these failures. Is there some better way around it? We'd e.g. be fine not loading images or webfonts in most tests, or at least nor raising if they haven't loaded quickly.

**Comment by henrik** [comment]
Heh, so about the lorempixel.com images, turns out they take aaaages to load, so that explains that. Though it'd still be nice with a way to disable loading (remote) images.

**Comment by route** [comment]
@henrik You can blacklist some urls with https://github.com/machinio/cuprite#url-blacklisting--whitelisting

**Comment by henrik** [comment]
@route Thank you! Will explore that. Appreciate it.
