### ISSUE TITLE
No test coverage badge

### ISSUE THREAD

**Issue by Valve** [machinio/cuprite#20]
You don't seem to have a test coverage badge and it's unclear if specs are all green and if it's safe to use your project.

**Comment by iainbeeston** [comment]
I've been trying to get the build passing on [Travis](https://travis-ci.org/). I'm pretty close, but there are still some intermittent issues to fix.

**Comment by iainbeeston** [comment]
#27 is my attempt to add publicly visible CI and a build badge

**Comment by Valve** [comment]
thanks @iainbeeston !
