### ISSUE TITLE
Auto-discover Google Chrome on macOS

### ISSUE THREAD

**Issue by sj26** [machinio/cuprite#23]
It would be nice if cuprite discovered my locally installed Google Chrome in the default location on macOS, like selenium etc.

```
$ rspec
Cliver::Dependency::NotFound:
  Could not find an executable `chrome`. Try to make it available on the PATH or set environment varible for example BROWSER_PATH="/Applications/Chromium.app/Contents/MacOS/Chromium"

$ BROWSER_PATH=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome rspec ...
... rspec output ...
```

**Comment by route** [comment]
@sj26 Totally agree, didn't pay attention to it much while developing

**Comment by sj26** [comment]
Ps this project looks super awesome!! I’ve been hoping someone would do this soon! 🙇🏻

**Comment by route** [comment]
Thank you) Glad you like it! Yea the idea was in the air we just needed it badly so we started implementing it :)

**Comment by dreyks** [comment]
we can take a look at how selenium does it

https://github.com/nu7hatch/selenium-webdriver/blob/master/lib/selenium/webdriver/chrome/launcher.rb#L113

btw, thx for the project. i needed it but knew I'd be too lazy to do that

the ruby-weekly mailing list could've attracted people here, so maybe we can help you moving it forward

**Comment by route** [comment]
@dreyks thanks, would appreciate it!

**Comment by edzhelyov** [comment]
@route what's the reasons to go directly to Chrome instead of the using the Selenium version?
In my company we changed recently from poltergeist to selenium headless chrome and the only issue was somehow a bit slower specs, so I'm curious why you needed it that badly?

**Comment by dreyks** [comment]
People don't like java. why have an additional proxy if your can avoid it? also selenium or rather chromium has limited capabilities compared to using bare CDT protocol, such as lack of header management, js environment management, network and other cool things

**Comment by iainbeeston** [comment]
FYI selenium webdriver is licensed under the apache 2 license, so they shouldn't mind if you reuse their list of locations (it might require disclaiming in the readme where the list came from though?)
