### ISSUE TITLE
Is `rack >= 2.0.6` dependency really needed?

### ISSUE THREAD

**Issue by vizcay** [machinio/cuprite#25]
I've tried to test this with a 5yo Rails v4.2.0 app, but that dependency wasn't too hard to met.

https://www.reddit.com/r/rails/comments/ahmbp0/we_switched_from_poltergeist_to_chromedriver_and/

**Comment by route** [comment]
@vizcay I think we don't need it at all in the gemspec. I'll remove it and you can try using the project from github `gem "cuprite", github: "machinio/cuprite"` before we release new version.

**Comment by route** [comment]
done, try it and let me know if everything is ok
