### ISSUE TITLE
#send_keys is failing when passing a symbol

### ISSUE THREAD

**Issue by vizcay** [machinio/cuprite#31]
According to capybara docs (https://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FNode%2FElement:send_keys), it should allowed to send a key event in the form of `element.send_keys :tab`. It looks like is only expecting a string:

```
     NoMethodError:
       undefined method `each_char' for :tab:Symbol

     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-0efa3f9ffbd4/lib/capybara/cuprite/browser/input.rb:64:in `send_keys'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-0efa3f9ffbd4/lib/capybara/cuprite/node.rb:17:in `command'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-0efa3f9ffbd4/lib/capybara/cuprite/node.rb:179:in `send_keys'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/element.rb:239:in `block in send_keys'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/element.rb:239:in `send_keys'
     # ./spec/features/presupuesto/editor/detalles_spec.rb:22:in `block (3 levels) in <top (required)>'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/session.rb:341:in `within'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/rspec/matcher_proxies.rb:14:in `within'
```

**Comment by route** [comment]
`send_keys` doesn't support any fancy keys right now, it's not implemented yet. PRs are always welcome ;)

**Comment by vizcay** [comment]
@route works like a charm.. 🎉 I have a few issues to close on my side and I will be able to submit a complete comparison betweeen chromedriver, selenium firefox, poltergeist and cuprite with an application that has 886 feature specs!

**Comment by route** [comment]
@vizcay nice! what are those issues?

**Comment by jmgarnier** [comment]
@vizcay Nice :) would you mind adding a comment to this issue with the link of your comparison please?

**Comment by vizcay** [comment]
@jmgarnier 

https://www.reddit.com/r/rails/comments/aoz1i3/run_dont_walk_to_switch_to_cuprite_test_driver/

**Comment by jmgarnier** [comment]
Thanks @vizcay ! Strange, when we switched from phantomjs / poltergeist to selenium  + chrome driver headless, we had faster (and less buggy) tests.

This is kind of subject which will be interesting for @thbar
