### ISSUE TITLE
can websocket-driver ~0.7 be relaxed to >= 0.6.5 to support Rails 5.1

### ISSUE THREAD

**Issue by McRip** [machinio/cuprite#32]
actioncable 5.1.6.1 (current actioncable release for Rails 5.1) has a dependency to `websocket-driver ~> 0.6.1` which is currently resolved to `0.6.5`.
By relaxing the dependency to `>= 0.6.5` we could add Rails 5.1 support.

Thanks for looking into this issue.

**Comment by route** [comment]
Sounds good to me!

**Comment by route** [comment]
FIxed in #35
