### ISSUE TITLE
undefined method `map' for "(cyclic structure)":String

### ISSUE THREAD

**Issue by iainbeeston** [machinio/cuprite#37]
I have code in a capybara feature spec that looks like this:

```ruby
find('header', match: :first)
```

and I'm calling it on a page with html like this:

```html
<html>
  <body>
    <header>
      <h1>Enter details</h1>
    </header>
  </body>
</html>
```
It should return `"Enter details"`, but instead it's raising an error in cuprite (I'm using master):

```
NoMethodError:
       undefined method `map' for "(cyclic structure)":String
       Did you mean?  tap
     # /Users/iain/.gem/ruby/2.5.3/bundler/gems/cuprite-be6d0412614a/lib/capybara/cuprite/browser.rb:253:in `find_all'
     # /Users/iain/.gem/ruby/2.5.3/bundler/gems/cuprite-be6d0412614a/lib/capybara/cuprite/browser.rb:72:in `find'
     # /Users/iain/.gem/ruby/2.5.3/bundler/gems/cuprite-be6d0412614a/lib/capybara/cuprite/driver.rb:68:in `find'
     # /Users/iain/.gem/ruby/2.5.3/bundler/gems/cuprite-be6d0412614a/lib/capybara/cuprite/driver.rb:76:in `find_css'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/node/base.rb:98:in `find_css'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/queries/selector_query.rb:137:in `find_nodes_by_selector_format'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/queries/selector_query.rb:102:in `block in resolve_for'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/node/base.rb:77:in `synchronize'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/queries/selector_query.rb:101:in `resolve_for'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/node/finders.rb:291:in `block in synced_resolve'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/node/base.rb:82:in `synchronize'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/node/finders.rb:286:in `synced_resolve'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/node/finders.rb:33:in `find'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/session.rb:728:in `block (2 levels) in <class:Session>'
     # /Users/iain/.gem/ruby/2.5.3/gems/capybara-3.7.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/support/capybara_helpers.rb:166:in `first_header'
     # ./spec/features/my_spec.rb:259:in `block (2 levels) in <top (required)>'
```

This is failing on [`Browser#find_all`](https://github.com/machinio/cuprite/blob/be6d0412614a9e764663ddfefbed39c24a205d28/lib/capybara/cuprite/browser.rb#L245), which is being passed `:css` to the method param, and `"header"` to the selector param (within is `nil`). What is being returned from the call to `evaluate` is the string `"(cyclic structure)"`, but the code seems to expect an enumerable object.

**Comment by route** [comment]
Fills like a bug, thought I'm not sure where. Could you reproduce it with simple test? Also returning something like a cyclic object isn't good also, so maybe you could modify your test so it returns part of the object rather than the whole object. But we need to fix this case anyway

**Comment by iainbeeston** [comment]
I'm struggling to reproduce this unfortunately, although I'm still trying different things.

It seems to fail when capybara tries to find a react.js component. Then when cuprite calls `isCyclic()` on the DOM node of the component, `JSON.stringify()` throws a `TypeError: Converting circular structure to JSON` error.

As I'm looking at the code for this, should `Browser::Runtime#reduce_props` throw an error when it is called with a cyclic object?  Currently it returns a string when the object is cyclic, but an array if not, which is why I see the error above. Perhaps something explaining what the user can do to resolve the issue, or why it's a problem? (That will not fix my issue but it might be helpful to other developers in future who hit this issue)

**Comment by iainbeeston** [comment]
I've managed to reproduce it in a test app here:

https://github.com/iainbeeston/cuprite-test

It seems to be that if I ask capybara/cuprite to find a react component, it gets the cyclic structure error. In the test app I have an example that checks the contents of a react component that just renders `<tt>Greeting: Hello from react-rails.</tt>`. I would have thought that this isn't a cyclic DOM node, but I get the error. If I use selenium-webdriver, the example passses.

I'm not sure why a Node that is rendered by react would lead to a cyclic structure error when `JSON.stringify()` is called on it, but I wonder if there's another way for cuprite to stringify DOM Nodes?

**Comment by iainbeeston** [comment]
I forgot to say, but I set up travis CI for the test app, so you can see the test failure:

https://travis-ci.org/iainbeeston/cuprite-test/builds

**Comment by iainbeeston** [comment]
I wonder if in index.js Cuprite should avoid calling `JSON.stringify` directly, but convert it's NodeList to html first, then back to a NodeList, so that it only serializes the html of the nodes, not any other properties that might have been added to it at runtime...

**Comment by iainbeeston** [comment]
Actually, I'm thinking that now if `JSON.stringify` could be called with a custom replacer argument, that filters out anything that is not an `instanceof Node`. That might work.

**Comment by route** [comment]
@iainbeeston  thanks for the application, could you please set env CUPRITE_DEBUG=true so that we can see devtools protocol, that should ease it a lot

**Comment by iainbeeston** [comment]
@route I've done that now. You should be able to see the output on Travis.

FYI You can reproduce locally on any web page using react, if in the developer console you call `JSON.stringify(document.querySelectorAll(<SELECTOR_FOR_REACT_COMPONENT>))` (this is the equivalent to what `Cuprite.isCyclic()` is doing)

**Comment by route** [comment]
Thank you. Could you please try returning something like `return to.is_a?(Hash) ? "(cyclic structure)" : ["(cyclic structure)"]` from there [runtime](https://github.com/machinio/cuprite/blob/master/lib/capybara/cuprite/browser/runtime.rb#L148)
would your test pass? or it' doesn't make any sense

**Comment by iainbeeston** [comment]
I don't think that makes sense - that would resolve the error thrown above by returning an array, but the underlying issue is that Curprite cannot serialize elements on the page created by react, and so specs cannot interact with or make assertions about react components.

**Comment by route** [comment]
@iainbeeston the thing is even in poltergeist it wasn't possible https://github.com/teampoltergeist/poltergeist/blob/38b1128c8c51fbeef9bfd2f8cf3cb9b2629a0272/spec/integration/session_spec.rb#L534 the object was returned but partially. I used to have code that made that test passing but it was too annoying because every time you ask chrome for an object it returns new one no matter the object is the same so in order to traverse cyclic object there were too many interactions between JS world and Chrome so that I have to remember all traversed objects in JS. You can see how it was before https://github.com/machinio/cuprite/commit/c911e866b2a43cce36c9b58f5f6fe533418ff85f

**Comment by iainbeeston** [comment]
I see!

I have an idea for this, though it might not work. I'll see if I can try it over this weekend

**Comment by route** [comment]
@iainbeeston how did this test work on selenium?

**Comment by iainbeeston** [comment]
@route It works perfectly on selenium. I've duplicated the same example and made it run with selenium on travis and it passes. (I tried to do it with poltergeist too but I couldn't get poltergeist to work with react because it needs a number of javascript polyfils)

**Comment by route** [comment]
Got it, I need to take a look closer seems pretty serious. Finishing full support of `send_keys` right now

**Comment by iainbeeston** [comment]
@route I might have a solution. Can you explain to me why cuprite needs to check whether an object is cyclic at all?

When I read the code, it looks like Cuprite checks whether an object is cyclic before it calls `Runtime.getProperties()` (which is in the chrome API) to get the javascript properties of an object. If it is cyclic, `Runtime.getProperties()` is never called. But so long as `Runtime.getProperties()` can handle cyclic objects I don't think Cuprite needs to check this at all?

I've made a branch of cuprite that removes these checks (see the changes [here](https://github.com/machinio/cuprite/compare/master...iainbeeston:allow-cyclic-objects)), and I've updated my test app to use that, and now the tests pass, which to me suggests that Chrome CAN handle this without cuprite having to check explicitly. However, it's possible I'm misunderstanding what the cyclic check is for?

**Comment by route** [comment]
@iainbeeston what about this test `ignores cyclic structure errors in evaluate_script`? it should exhaust stack frame recursively if you remove cyclic check.

**Comment by iainbeeston** [comment]
@route Yes - if I leave that test in, it recurses infinitely (in ruby) then crashes once the maximum number of stack frames is reached. However, the test is a strange one - the `isCyclic` check is only ever run on `NodeList` objects, but the test does not use a `NodeList` - instead it uses a plain old javascript object. Ideally it should test a `NodeList` from a real web page, but I can't think of a way to construct one that is cyclic. This makes me wonder if this is ever something that could occur, with a real web page tested with capybara?

**Comment by route** [comment]
@iainbeeston I guess we can just drop this check on NodeList as it is like an Array but has nodes as elements and for elements we use internal representation supported by devtools protocol like `"{\"injectedScriptId\":2,\"id\":25}"` so it never be cyclic unlike array which can have a reference to itself: `a = []; a.push(a)`

**Comment by route** [comment]
Just pushed commit https://github.com/machinio/cuprite/commit/41c18848431ecf4a234e197429861e722db81cef your test is passing

**Comment by iainbeeston** [comment]
@route That's a good solution.

The build on my branch was passing because I was using a fork of cuprite that had the cyclic check removed. However, I have updated it to use cuprite master now (with your fix) and it passes. I'll close this issue.

Thanks for your help!

**Comment by route** [comment]
Thanks for informing! That was a critical one I think!

**Comment by iainbeeston** [comment]
@route I'm really sorry but I'm going to have to reopen the issue because I've founda nother situation where it happens 😞 

It seems that if I use capybara's `click_on` method, to click a link that is rendered by react.js, I still see the original issue. It seems that the fix does not work with `click_on`, because with `click_on` we have an `Array` of `Node` objects, not a `NodeList`. I haven't been able to produce a test case yet. However, I suspect that this is because in `index.js` the `find` method returns an array of `Node`s if xpath is used to find an element but if css is used a `NodeList` is returned, and we are not handling the array case.

**Comment by iainbeeston** [comment]
@route I've made a proposal for a fix to this in #40 - where I make sure `find()` always returns an array of `Node`s and made `isCyclic()` always return false for this case. For me that handles both the original test failure (for finding text on the page rendered by react.js) and the new test failure (using `click_on` with links rendered by react.js)

**Comment by route** [comment]
Haha) no problem, looks good to me anyway!

**Comment by iainbeeston** [comment]
Cool, thanks!
