### ISSUE TITLE
Capybara::Node::Element#click not working

### ISSUE THREAD

**Issue by vizcay** [machinio/cuprite#38]
I have a bunch of tests (~25) that depend on this functionality (working flawlessly with Geckodriver, Chromedriver and PhantomJS), and are failing with:

> Capybara::Cuprite::TimeoutError:
>   Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Cuprite :timeout option to a higher value might help.
> 

But has nothing to do with a timeout, looks like the`#click` method is not working because If I debug before the failing line and do `find('#elemet_id')` or `find('.element_class')` the node is returned.

For example this happens with this helper:

```ruby
  def force_blur_focus
    page.find('body').click
  end
```

That I use to force the blur of the focus in the current input.

Complete backtrace:

```
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/client.rb:39:in `pop'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/client.rb:39:in `block in wait'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/client.rb:39:in `wait'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/page.rb:185:in `command'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/runtime.rb:159:in `cyclic?'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/runtime.rb:147:in `reduce_props'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/runtime.rb:128:in `handle'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser/runtime.rb:33:in `evaluate'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser.rb:248:in `find_all'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/browser.rb:78:in `find_within'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/node.rb:17:in `command'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/node.rb:36:in `find'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/cuprite-960e1b481492/lib/capybara/cuprite/node.rb:42:in `find_xpath'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/base.rb:108:in `find_xpath'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/queries/selector_query.rb:149:in `block in resolve_for'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/queries/selector_query.rb:145:in `resolve_for'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/matchers.rb:687:in `block in _verify_selector_result'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/matchers.rb:686:in `_verify_selector_result'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/matchers.rb:93:in `assert_selector'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/rspec/matchers.rb:68:in `block in matches?'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/rspec/matchers.rb:27:in `wrap_matches?'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/rspec/matchers.rb:68:in `matches?'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/pablo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
```

**Comment by route** [comment]
@vizcay could you please run your test with `CUPRITE_DEBUG=true bundle exec rspec ...` option turned on?

**Comment by vizcay** [comment]
@route sure! Wasn't able to upload here because it was more than 64k.. I've send it to your personal email.

**Comment by route** [comment]
@vizcay most likely you have an alert which you didn't handle with accept_confirm or dismiss_confirm after clicking at a.btn.btn-mini.retencion_ganancias_calcular
```
{"url":"http://127.0.0.1:56656/empresas/6861/pagos/new","message":"Se ha producido un error en el servidor, cont\u00E1ctese con el soporte t\u00E9cnico.","type":"alert","hasBrowserHandler":false,"defaultPrompt":""}
```

**Comment by vizcay** [comment]
@route as a matter of fact, your are right. When I get the timeout is because there is an alert "blocking" the page. Now, since this doesn't happens with selenium (chromedriver o geckodriver both work fine on those tests) I did a little more research and reduced the problematic error to this:

```ruby
    it 'alert date is out of range' do
      visit new_invoice_path(test_business)
      message = accept_alert do
        fill_in 'invoice_date', with: input_date(Date.current - 31)
        find('body').click # => HANGS HERE
      end
      expect(message).to eq 'Date is out of 30 days range.'
    end
```

Now the spec with cuprite hangs at the line `find('body').click` as described, because the alert is already present on the page. But, with selenium, to force the alert (that is fired in the callback of the blur event of the invoice_date input) I need to "force the lost of focus" by the means of `find('body').click` (or clicking other input, whateve).

So, the question is,

* This is intendend behaviour? A `#fill_in` should automatically fire a `blur` DOM event after completing it's job? I don't think so, at least is not the same that a human does automatically.

* This behaviour happens for all inputs or only `input[type=date]`? This is because I see this error happens only on date inputs.. but I'm not sure if the test suite has this same condition for other type of inputs.

**Comment by route** [comment]
I believe cuprite has the same behavior as poltergeist and I think it's correct. Filling in any given input not only should trigger blur after filling but also first of all focus an element as well as remove previous value, so it's a lot of additional work. I think it's complete and `find('body').click` is an extra in my opinion.

**Comment by vizcay** [comment]
That's true, phantomjs works the same way (but it is not checking the alert it's open that cuprite is doing  right so the test passes). I will solve it by always using `force_blur_focus`:

```
  def force_blur_focus
    page.find('body').click unless ENV['CUPRITE']
  end
```

Regarding which behaviour is better I'm not sure but IMHO trying to be as compatible as possible with selenium is not a bad idea. I will close this issue as the latter findings show that the find(xxx).click functionality is working right.

**Comment by route** [comment]
@vizcay poltergeist accepts all popups by default, cuprite doesn't and in chrome it results in stop the world behaviour that waits for action. I think instead of timeout error it would be nice to see an error about unhandled modal window. To stick with selenium or poltergeist is an open question if you have 5k tests that worked on poltergeist it will be easier to switch to cuprite if behaviour is similar, same thing vice versa it depends. Though the driver claimed to be close poltergeist :)

**Comment by carloshdelreal** [comment]
My solution was to start using `driven_by :selenium,`
