### ISSUE TITLE
Is proxy supported?

### ISSUE THREAD

**Issue by thbar** [machinio/cuprite#39]
I'm trying to configure `cuprite` in a way that would use [puffing-billy](https://github.com/oesmith/puffing-billy) as a proxy (this is useful to mock any request, including external ones like Stripe or Recurly).

I attempted to do this:

```ruby
require 'capybara/cuprite'
Capybara.javascript_driver = :cuprite

Capybara.register_driver :custom_billy do |app|
  driver = Capybara::Cuprite::Driver.new(app, {})
  driver.set_proxy(Billy.proxy.host, Billy.proxy.port)
  driver
end
```

Apparently the call to `set_proxy` raises a `NotImplementedError`.

Is this expected?

Many thanks!

**Comment by route** [comment]
@thbar I can add proxy support pretty quick but there's one downside you can set it only when browser starts and there's no way currently to change it on fly, as Chrome doesn't support it https://github.com/cyrus-and/chrome-remote-interface/issues/152

**Comment by thbar** [comment]
@route is the browser starting one per test suite? Or instead (as I assume) once per test? If it's once per test, it's perfectly acceptable as a limitation (& not causing any trouble in my case at least).

**Comment by thbar** [comment]
To clarify: I use multiple drivers in this test suite: one is `custom_billy` (specs are tagged with `driver: :custom_billy), and these ones are all using a proxy. The other one will be a "regular" cuprite, so a différent driver instance etc.

If I understand well this means that each "driver type" will start a browser once, and it will be fast enough.

In all cases, I can provide feedback if you implement this (but don't feel forced to do so if you feel it's not the good moment or not a good feature! my use case is pretty exotic!).

**Comment by route** [comment]
@thbar in fact we needed proxies too, this was the beginning of `cuprite` we wanted too many exotic features :) will roll it out in an hour or so I think ;)

**Comment by route** [comment]
I pushed changes https://github.com/machinio/cuprite/commit/9ddeddf82d683412c3cd47c3af650fb697487fc1 for basic support, though it is missing auth and runtime proxy rotation

**Comment by thbar** [comment]
@route thanks! I will try this out & will report back.

**Comment by thbar** [comment]
@route I was able to set the proxy, and it mostly worked, but my suite is regressing for some weird reason at this point. I cannot pinpoint it exactly at this point, but will investigate!

I will still close, because I believe the proxy support is already in master & providing value as is. Thanks!
