### ISSUE TITLE
"set_proxy" doesn't seem to have an effect for external resources

### ISSUE THREAD

**Issue by thbar** [machinio/cuprite#44]
Similarly to what's happening on the `apparition` driver (https://github.com/twalpole/apparition/issues/2), and I presume for the same reasons (both use CDP afaik), if one uses `set_proxy`, and a given page includes external resources (e.g. a `<script>`, but probably also JSONP calls etc), these calls won't go through the proxy.

This can be problematic for instance if someone is using [puffing-billy](https://github.com/oesmith/puffing-billy), a rewriting web proxy which is very useful to e.g. mock out javascript calls to external payment systems (Stripe/Recurly etc).

The `poltergeist` driver (from which I'm migrating off, because `phantomjs` is EOL), was working differently & all externals calls were going through the proxy, hence allowing to stub out those calls.

I'm raising this point since we'll see more people migrating off `phantomjs` in the next few months!

I've created a self-contained reproduction (which also shows the behaviour of `poltergeist`) here:

https://github.com/thbar/repro-bug-proxy

**Comment by route** [comment]
@thbar you can pass options to the browser as: `browser_options: { "ignore-certificate-errors" => nil }`

**Comment by thbar** [comment]
Thanks!
