### ISSUE TITLE
Strange field reset issue

### ISSUE THREAD

**Issue by lstanden** [machinio/cuprite#49]
Trying to find a good way to create a test case for this, but thought I'd ask for suggestions since I got a bit stuck.

 I have a test which does something like:

```
visit some_page
click 'submit'
assert_equal 'Some error message', find('.some-element').text

fill_in 'name', with: 'some test'
fill_in 'body', with: 'some message'
click 'submit'
assert_equal 'Success', find('.some-element').text
```

The line with `fill_in 'name'` is not throwing any kind of error, but the form field is blank when the submit button is clicked.

For context, I'm attempting to covert an entire test suite from poltergeist to cuprite.

Any suggestions?

**Comment by lstanden** [comment]
Ok, I actually managed to debug this, so I know what's happening.

Basically this appears to be an interaction between React which isn't playing nicely.  It looks like the value is being set of the HTML element, however the onchange event isn't firing in React, which means the state is not being updated, leading to the field being reset when the component re-renders.

Normal usage of the form in a browser *does* trigger the change event, so this is definitely the process of triggering a change event causing the issue.

From what I can see in the Cuprite code, it basically does this for an input field:

```
element = document.querySelector('input[name="something"]');
element.value = 'test';
event = document.createEvent("HTMLEvents");
event.initEvent("change", true, false);
element.dispatchEvent(event);
```

Not sure how to fix this as yet, but this is definitely not triggering the onChange handler in React.

**Comment by lstanden** [comment]
Here is a Codesandbox which demonstrates the problem: 
https://codesandbox.io/s/mo2okv31w9

**Comment by lstanden** [comment]
I just updated the codesandbox with a solution courtesy of cypress https://github.com/cypress-io/cypress/commit/b38d028a60e07480ef63cf760c3f5c763e8a935f#diff-ed17d49edc10403752ba3d786a7512dbR33

Basically you need to call the native setter, which should then work with any framework (not just React).

```
var nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set
	
var nativeTextareaValueSetter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, "value").set
	
function setValue (el, val) {
  if (el.tagName.toLowerCase() === "input") {
    return nativeInputValueSetter.call(el, val)
  }
  return nativeTextareaValueSetter.call(el, val)
}	
```

**Comment by route** [comment]
@lstanden would you mind opening a PR?

**Comment by lstanden** [comment]
Was working on that since I found the fix.  Just opened.
