### ISSUE TITLE
rspec fail if CUPRITE_DEBUG is on

### ISSUE THREAD

**Issue by lacostej** [machinio/cuprite#50]
Platform: Mac
Ruby 2.5.0
Chrome

````
bundle exec rspec spec/unit/

Failures:

  1) Capybara::Cuprite::Browser logs requests and responses
     Failure/Error: expect(logger.string).to include("<html><head></head><body></body></html>")
       expected "" to include "<html><head></head><body></body></html>"
     # ./spec/unit/browser_spec.rb:15:in `block (2 levels) in <module:Cuprite>'

Finished in 2.7 seconds (files took 0.79745 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/unit/browser_spec.rb:8 # Capybara::Cuprite::Browser logs requests and responses
````

**Comment by route** [comment]
I've never seen it failing on any platform, are you on mac or windows?

**Comment by lacostej** [comment]
I think the issue is that the logger is redirected when CUPRITE_DEBUG is on and the test is unable to read from the logger anymore.

**Comment by route** [comment]
I think if someone set logger we should prioritize it as they expect output to be there. They expect debug info to be in that IO so that CUPRITE_DEBUG is redundant as it eventually is the same but right on STDOUT

**Comment by route** [comment]
Fixed in https://github.com/machinio/cuprite/commit/e8156509d36e45851e7ba500c801ebdcbabd7825
