### ISSUE TITLE
Bringing back the "no-sandbox" process option

### ISSUE THREAD

**Issue by niezbop** [machinio/cuprite#57]
I have had errors when running with a non parametrized user because of the no-sanbox option. Because we do not necessarily want to run with a configured user, I'm trying to get this implemented in the codebase, but I'd like your advise. Would it be good if it was an opt-out parameter in the process constructor?

**Comment by route** [comment]
I think we need a general way to opt-out any option like --headless and so on, sounds good to me though for this one in particular.

**Comment by lstanden** [comment]
FWIW you can enable no-sandbox.  This is what I'm using:

```
Capybara.register_driver :cuprite do |app|
  Capybara::Cuprite::Driver.new(
    app,
    js_errors: true,
    headless: true,
    window_size: [1366, 768], # most popular window size (35%)
    browser_options: {
      'no-sandbox': nil
    }
  )
end
```

**Comment by lacostej** [comment]
@lstanden good to know! @niezbop maybe we just want to document this instead of adding more code.

**Comment by niezbop** [comment]
Thanks @lstanden I think that is exactly what we need! I didn't realize we could configure Cuprite this way! I'm closing the issue
