### ISSUE TITLE
Non replicable test failure

### ISSUE THREAD

**Issue by niezbop** [machinio/cuprite#62]
Heyo!

Related to #52 I'm running tests on my Windows machine to see if tests are still failing, and I have had a test fail, but not always:

```
4) Capybara::Cuprite::Driver javascript errors propagates a synchronous Javascript error on the page to a ruby exception
     Failure/Error:
       expect do
         driver.execute_script "omg"
       end.to raise_error(JavaScriptError, /ReferenceError.*omg/)

       expected Capybara::Cuprite::JavaScriptError with message matching /ReferenceError.*omg/, got #<NoMethodError: undefined method `first' for nil:NilClass> with backtrace:
         # ./lib/capybara/cuprite/browser/targets.rb:9:in `initialize'
         # ./lib/capybara/cuprite/browser.rb:245:in `new'
         # ./lib/capybara/cuprite/browser.rb:245:in `targets'
         # ./lib/capybara/cuprite/driver.rb:94:in `execute_script'
         # ./spec/integration/driver_spec.rb:594:in `block (4 levels) in <module:Cuprite>'
         # ./spec/integration/driver_spec.rb:593:in `block (3 levels) in <module:Cuprite>'
         # ./spec/integration/driver_spec.rb:14:in `block (2 levels) in <module:Cuprite>'
     # ./spec/integration/driver_spec.rb:593:in `block (3 levels) in <module:Cuprite>'
     # ./spec/integration/driver_spec.rb:14:in `block (2 levels) in <module:Cuprite>'
```

Don't know if it's bad luck or something, but I wanted to let you know 🙂

**Comment by route** [comment]
@niezbop That's very rare intermittent issue, which is not possible by all means. I couldn't catch it locally but if you could catch it with `CUPRITE_DEBUG=true` env turned on it would be great, because Chrome should return at least one default target. Looks like race condition in Chrome.

**Comment by route** [comment]
I think I'm gonna close it for now as it doesn't look like an issue in cuprite, though if you catch it especially with debug option again please submit the log file. Thank you!

**Comment by TemaMix** [comment]
@route I wonder if you could possibly help me or give some advice. It seems  I have a similar issue with a gem is based on the cuprite 0.6.0.  And I have some tests where this issue appears regularly.  When I run this with ``` CUPRITE_DEBUG=true``` I have got the following result:
```
$ CUPRITE_DEBUG=true bundle exec rspec --seed 123  ./spec/browser_crawler_spec.rb
```
```
  with max_pages option specified
I, [2019-05-26T11:30:18.377566 #68999]  INFO -- : Visiting http://127.0.0.1:51081


>>> {"method":"Target.getTargets","params":{},"id":1}
    <<< {"id":1,"result":{"targetInfos":[]}}


>>> {"method":"Target.getTargets","params":{},"id":2}
    <<< {"id":2,"result":{"targetInfos":[]}}
F, [2019-05-26T11:30:18.645286 #68999] FATAL -- : undefined method `first' for nil:NilClass 
F, [2019-05-26T11:18:00.013574 #68930] FATAL -- : undefined method `first' for nil:NilClass 
ruby-2.6.1/gems/cuprite-0.6.0/lib/capybara/cuprite/browser/targets.rb:9:in `initialize'
ruby-2.6.1/gems/cuprite-0.6.0/lib/capybara/cuprite/browser.rb:241:in `new'
ruby-2.6.1/gems/cuprite-0.6.0/lib/capybara/cuprite/browser.rb:241:in `targets'
ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:224:in `page'
ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:224:in `visit'
ruby-2.6.1/gems/cuprite-0.6.0/lib/capybara/cuprite/driver.rb:31:in `visit' 

/spec/browser_crawler_spec.rb:49
```

Maybe, I do something wrong, but such errors appear constantly.
If you have time you can take a look at the code [here](https://github.com/DimaSamodurov/browser_crawler/tree/change-method-inspection-linksl) and also take a look at the failed spec file [here](https://github.com/DimaSamodurov/browser_crawler/blob/change-method-inspection-links/spec/browser_crawler_spec.rb). 

I hope it helps you find a solution.

Please let me know if you have other questions or concerns. Thank you!

**Comment by route** [comment]
Hi @TemaMix do you use windows too?

**Comment by TemaMix** [comment]
@route Nope, I have launched it inside Mac OS or Linux inside Docker.

**Comment by route** [comment]
I just merged one fix related to this issue, could you try using cuprite from master? Does it resolve the issue?

**Comment by TemaMix** [comment]
@route, Thank you for your rapidly answer.
I rerun tests from cuprite (master). However, the previous error is disappeared, but another error has appeared:
```
>>> {"method":"Target.getTargets","params":{},"id":4}
    <<< {"id":4,"result":{"targetInfos":[]}}
F, [2019-06-03T22:45:55.219225 #87709] FATAL -- : No target browser available 
 /Users/artemrumiantcev/.rvm/gems/ruby-2.6.1/bundler/gems/cuprite-8bde777fa687/lib/capybara/cuprite/browser/targets.rb:118:in `targets'
/Users/artemrumiantcev/.rvm/gems/ruby-2.6.1/bundler/gems/cuprite-8bde777fa687/lib/capybara/cuprite/browser/targets.rb:13:in `initialize'
/Users/artemrumiantcev/.rvm/gems/ruby-2.6.1/bundler/gems/cuprite-8bde777fa687/lib/capybara/cuprite/browser.rb:241:in `new'
/Users/artemrumiantcev/.rvm/gems/ruby-2.6.1/bundler/gems/cuprite-8bde777fa687/lib/capybara/cuprite/browser.rb:241:in `targets'
/Users/artemrumiantcev/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:224:in `page'
/Users/artemrumiantcev/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:224:in `visit'
/Users/artemrumiantcev/.rvm/gems/ruby-2.6.1/bundler/gems/cuprite-8bde777fa687/lib/capybara/cuprite/driver.rb:31:in `visit'
/Users/artemrumiantcev/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara/session.rb:276:in `visit'
```

**Comment by route** [comment]
What browser version do you use? I've never seen it failing that constantly ;)

**Comment by TemaMix** [comment]
I use Chrome with Version 74.0.3729.169 (Official Build) (64-bit). I have seen a capybara issue regarding Chrome 74 (https://github.com/teamcapybara/capybara/issues/2181) and rerun tests with these options, but errors are the same.

**Comment by route** [comment]
@TemaMix just out of curiosity did you try Chromium or other versions?

**Comment by TemaMix** [comment]
@route Thank you for your advice. It is worked! Hm, I will wait for the next Chrome version if it is one way.

**Comment by route** [comment]
@TemaMix no problem, glad it worked!
