### ISSUE TITLE
Chrome process did not produce websocket url within 1 seconds (RuntimeError)

### ISSUE THREAD

**Issue by gregoryduckworth** [machinio/cuprite#77]
Even after updating the cuprite declaration (as seen below) we still get the error `Chrome process did not produce websocket url within 1 seconds (RuntimeError)`

```
Capybara.register_driver :cuprite do |app|
  Capybara::Cuprite::Driver.new(app, {
  headless: true,
  inspector: true,
  process_timeout: 5,
  url_blacklist: [
    'blacklisted_url'
  ],
  browser_options: {
    'ignore-certificate-errors' => true
  },
  timeout: 120
})
end
```

Is there some configuration missing?

**Comment by route** [comment]
@gregoryduckworth what is you OS? Do you have Chrome in $PATH?

**Comment by route** [comment]
Can't help without additional info.

**Comment by zuburqan** [comment]
I am having the same issue, the environment is:

OS: 4.1.12-61.1.28.el7uek.x86_6 (RHEL 7)
Browser: Chromium v73.0.3683.86
Chromedriver: v73.0.3683.86

Chromium and chromedriver is already in the $PATH

Configuration is:

`
Capybara.register_driver :cuprite do |app|
  options = {window_size: [1440, 900]}
  options[:headless] = false if ENV["CUPRITE_HEADLESS"] == "false"
  options[:slowmo] = ENV["CUPRITE_SLOWMO"].to_f if ENV["CUPRITE_SLOWMO"]

  Capybara::Cuprite::Driver.new(app, options)
end
`

**Comment by zuburqan** [comment]
I am having the same issue, the environment is:

OS: 4.1.12-61.1.28.el7uek.x86_6 (RHEL 7)
Browser: Chromium v73.0.3683.86
Chromedriver: v73.0.3683.86

Chromium and chromedriver are already in the $PATH

Configuration is:

```
Capybara.register_driver :cuprite do |app|
  options = {window_size: [1440, 900]}
  options[:headless] = true
  Capybara::Cuprite::Driver.new(app, options)
end
```

**Comment by route** [comment]
@zuburqan did you also try to increase process_timeout?

**Comment by gregoryduckworth** [comment]
Sorry about the slow reply, I've had this in docker using the versions:
```
Google Chrome 72.0.3626.109

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```
and can confirm that it is in the $PATH.

**Comment by route** [comment]
@gregoryduckworth there's one remark in README now for docker https://github.com/machinio/cuprite#running-in-docker

**Comment by gregoryduckworth** [comment]
Thanks! Working now.

**Comment by ndbroadbent** [comment]
Sorry to comment on an old issue, but hopefully this might help someone else! I was struggling with getting cuprite to control Chrome on GitHub Actions, and it turns out that the default `process_timeout` of 1 second is just too short so Chrome didn't have time to start on the CI servers. (The `no-sandbox` option is also important.) Here's my working `:cuprite` driver for Capybara:

```
  Capybara.register_driver(:cuprite) do |app|
    browser_options = {}
    browser_options['no-sandbox'] = nil if ENV['CI']
    headless = !ENV['SHOW_BROWSER']
    Capybara::Cuprite::Driver.new(
      app,
      browser_options: browser_options,
      headless: headless,
      process_timeout: 20
    )
  end
  Capybara.javascript_driver = :cuprite
```

**Comment by route** [comment]
@ndbroadbent I'll increase defaults
