### ISSUE TITLE
Capybara.default_host and Capybara.app_host don't set the Host header

### ISSUE THREAD

**Issue by pedantic-git** [machinio/cuprite#79]
Hi Machinio - thanks for a great driver!

In switching from Selenium I note that I can't use Capybara.default_host or Capybara.app_host to ensure the Host header is set correctly. My app responds differently depending on which hostname is used so it misbehaves with the cuprite driver.

Are there plans to introduce this feature? I could have a go at fixing it myself but I've had a browse of the cuprite code and I'm not sure I understand the best way to do this.

Thanks for your help!

**Comment by route** [comment]
Hi @pedantic-git thanks for kind words! Could you please show the scenario and failing test, it should work very well I guess. We implemented everything Capybara requires.

**Comment by pedantic-git** [comment]
My apologies - I just tried to reproduce this in a clean environment and it worked fine. It must have been my error somewhere. Please ignore me!

**Comment by route** [comment]
Ok haha, thanks)
