### ISSUE TITLE
Browser hang when running single test file

### ISSUE THREAD

**Issue by n-rodriguez** [machinio/cuprite#80]
For example:

When running `bundle exec rspec spec/system/back_office` tests run 

but when running `bundle exec rspec spec/system/back_office/customers_spec.rb` it runs the first test then it hangs forever.

**Comment by route** [comment]
Sorry but without CUPRITE_DEBUG it will be fortune-telling, please run your tests with `CUPRITE_DEBUG=true bundle exec rspec spec/system/back_office/customers_spec.rb` and send the output. Thanks!
