### ISSUE TITLE
Capybara::Cuprite::Browser::Targets#targets is sometimes empty during Browser init

### ISSUE THREAD

**Issue by wojtha** [machinio/cuprite#84]
Hello!

We are experiencing flaky tests on at least 2 local dev machines because of `Capybara::Cuprite::Browser::Targets#targets` being empty. However we are not experiencing this on our CI server (Codeship). (So perhaps it could be somehow environment / Chrome version related...)

It blows up during first touch with `page.browser`. Previously we have had `page.driver.browser.url_whitelist = ['127.0.0.1']` in the config. So it usually exploded there. After we placed this to driver config it explodes later in the test execution - e.g. during first `visit` command within the example.

macOS 10.14.4
Cuprite ver 0b985fa6a8e5
Chrome version 74.0.3729.157
[cuprite_debug_20190523.txt](https://github.com/machinio/cuprite/files/3212409/cuprite_debug_20190523.txt)

Setup
```ruby
Capybara.register_driver :cuprite_debug do |app|
  options = {
    headless: true,
    inspector: true,
    process_timeout: 5,
    browser_options: {
      'ignore-certificate-errors' => true
    },
    timeout: 120,
    url_whitelist: ['127.0.0.1'],
  }
  Capybara::Cuprite::Driver.new(app, options)
end
```

Stack trace
```
NoMethodError: undefined method `first' for nil:NilClass
/Users/wojtha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/cuprite-0b985fa6a8e5/lib/capybara/cuprite/browser/targets.rb:9:in `initialize'
/Users/wojtha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/cuprite-0b985fa6a8e5/lib/capybara/cuprite/browser.rb:241:in `new'
/Users/wojtha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/cuprite-0b985fa6a8e5/lib/capybara/cuprite/browser.rb:241:in `targets'
/Users/wojtha/.rbenv/versions/2.5.3/lib/ruby/2.5.0/forwardable.rb:223:in `page'
/Users/wojtha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/cuprite-0b985fa6a8e5/lib/capybara/cuprite/browser.rb:189:in `url_whitelist='
/Users/wojtha/Code/inm/portal/spec/support/config/capybara.rb:228:in `block (2 levels) in <main>'
```

**Comment by route** [comment]
Thank you @wojtha !
