### ISSUE TITLE
Chrome process did not produce websocket url within 1 seconds (RuntimeError)

### ISSUE THREAD

**Issue by andyryan** [machinio/cuprite#86]
I am trying to run Cucumber tests using cuprite for Capybara with the following set up

```
Capybara.register_driver :cuprite do |app|
  options = {js_errors: true, browser_options: {headless: true, "disable-gpu": true, "no-sandbox": true}}
  Capybara::Cuprite::Driver.new(app, options)
end
```
However I get the error 

> Chrome process did not produce websocket url within 1 seconds (RuntimeError)

I first tried to work around this by setting `process_timeout` to 30 seconds, but recevied another error (in less than 30 seconds)

> Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Cuprite :timeout option to a higher value might help. (Capybara::Cuprite::TimeoutError)

So i set the `timeout` option to 30 (supposedly the default) and everything works correctly.

So i'm not sure if this is a problem with defaults or setup.

> Mac OSX: 10.14.4
> Chrome version: 75.0.3770.100

**Comment by route** [comment]
@andyryan do you run your tests in Docker?

**Comment by andyryan** [comment]
no, this is just on my local machine

**Comment by route** [comment]
`no-sandbox` is only for docker so you can skip it. `headless` and `disable-gpu` should work by default. So looks like you don't have to pass any, did you try removing them all? Maybe `js_errors` has a bug I heard about mutex locking error in another issue bu didn't have time to check it. Could you please get rid of all of them and try if it works and then add one by one triaging the issue

**Comment by route** [comment]
Needs feedback, closing
