### ISSUE TITLE
Is remote access to chrome supported?

### ISSUE THREAD

**Issue by TemaMix** [machinio/cuprite#87]
I can't find any roadmap so decided to ask this question. I want to separate a main application and chrome to different docker containers therefor it is required a remote control under chrome, but I can't understand how to set up cuprite's configuration. 
Could you please give me advice may be I something miss?

**Comment by route** [comment]
@TemaMix yes we merged it in March. Is that what you are looking for? https://github.com/machinio/cuprite/issues/70 
https://github.com/machinio/cuprite/pull/75

**Comment by route** [comment]
In general you have to pass a url to cuprite and it won't spawn the process but instead will rely on existing one:

```
Capybara.register_driver :cuprite do |app|
  url = URI.parse("http://127.0.0.1:32001")
  Capybara::Cuprite::Driver.new(app, url: url)
end
```

**Comment by TemaMix** [comment]
Hi @route,

Thank you for your answer! It's really great work!) 

Could you please give more information about your release plans when you are going to publish gem with last changes on RubyGems?

**Comment by route** [comment]
I guess the only thing that bothers me is https://github.com/machinio/cuprite/issues/61
After coming up with some good solution I think there's nothing big to fix and we can release

**Comment by route** [comment]
Closing this then if you found what you need
