### ISSUE TITLE
url does not seem to pass through to Ferrum process

### ISSUE THREAD

**Issue by lstanden** [machinio/cuprite#97]
Not sure if I'm doing something wrong here, but I've tried passing through the `url` parameter to Cuprite, and it still spawns the Chrome process.  If there's an error occurring, I can't see any output related to the said error, and it simply seems to just not respect the parameter.

**Comment by route** [comment]
Hm it should have passed it, I’ll check tomorrow

**Comment by lstanden** [comment]
Actually, never mind... looks like I was having issues getting it to load the correct versions in the Gemfile.  Problem solved.
